steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'krisha1902/flask-api:$SHORT_SHA'
      - '.'

  # Step 2: Push the image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'krisha1902/flask-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
