steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['login', '-u', 'krisha1902', '-p', 'REMOVED_FOR_SECURITY']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'krisha1902/flask-api:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'krisha1902/flask-api:$SHORT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
