steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'krisha1902/flask-api:$SHORT_SHA'
      - '.'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
